### ISSUE TITLE
allow_url_fopen dependency

### ISSUE THREAD

**Issue by cozmalaurentiu** [pandy06269/blue-twilight#48]
Installing Blue Twilight Setup Files
•Checking PHP modules...
•Fetching Composer signature...

Warning: file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /public/install.php on line 140

Warning: file_get_contents(https://composer.github.io/installer.sig): failed to open stream: no suitable wrapper could be found in /public/install.php on line 140
Failed downloading the Composer signature from https://composer.github.io/installer.sig. 

Unable to set allow_url_fopen on shared hosting

**Comment by pandy06269** [comment]
Thanks for reporting this. Do you have shell/CLI access on your host?

The only way around this I can see is to ship a copy of the Composer installer with Blue Twilight - which is directly against the Composer project's recommendations, however I can't see another alternative.

**Comment by cozmalaurentiu** [comment]
No, my host is quite restrictive and i don't have ssh access.
 Would using curl instead of file_get_contents() be a solution?

**Comment by pandy06269** [comment]
Yep, that may work. Let me have a look tomorrow, I'll get you a replacement `install.php` file to try out.

**Comment by pandy06269** [comment]
Actually, just reading around - it seems Composer requires allow_url_fopen turned on due to its own use of `file_get_contents`.

https://github.com/composer/composer/issues/4740

I've zipped up the dependencies (which Composer installs) at the below URL. Download and unzip this on your own machine, then upload into the root folder of your Blue Twilight install - so you have:

- app
- bootstrap
- config
- ... etc. ...
- vendor (this is the contents of the zip file).

**Comment by pandy06269** [comment]
I've noticed you're accessing your system using "your-url/public/" - ideally your web hosting root (sometimes called www-root) should be pointed to the public folder, so you just access "your-url/".

However if you cannot do this, you'll need to amend your public/.htaccess file to have `RewriteBase /public/`.

**Comment by cozmalaurentiu** [comment]
root is pointed to public folder

After adding the folder i get 404 on
http://mydomain/photo/public/install/check

**Comment by pandy06269** [comment]
If your www-root is pointed to the public folder (within Blue Twilight's install directory), you don't need /public in the URL. Blue Twilight is a Laravel 5 application, which are designed to be at the root of a domain or subdomain (e.g. http://photos.mydomain or just http://mydomain -> which would be rooted at, e.g. `/file/system/path/blue-twilight/public`.)

Based on your URL, it looks like your www-root isn't pointing to Blue Twilight's public folder. 

To get your current URL working, you will need to modify your `public/.htaccess` to have a `RewriteBase` of `/photo/public/` - i.e.

`RewriteBase /photo/public/`

**Comment by cozmalaurentiu** [comment]
Yes, i had the subdomain pointing wrong, changed it to correct location.

System Requirements page is displayed with a warning

Maximum POST request size:                                                                                        Your post_max_size setting should be slightly bigger than your upload_max_filesize setting to allow for the HTTP header.
--

and when i click Continue i get

**Comment by cozmalaurentiu** [comment]
I enabled debug and this is the actual error:


(1/1)                                         FatalErrorException                                     Call to undefined method Illuminate\Session\Store::set()
--
in InstallController.php (line 58)

**Comment by pandy06269** [comment]
What version of Blue Twilight are you using?

**Comment by cozmalaurentiu** [comment]
2.1.0-beta.3

**Comment by pandy06269** [comment]
Brilliant thanks - I must have missed this in the Laravel 5.3 -> 5.4 upgrade that went into 2.1.0.

I'll raise a separate issue for it and close this one.
