### ISSUE TITLE
Create/manage album returns ErrorException

### ISSUE THREAD

**Issue by cozmalaurentiu** [pandy06269/blue-twilight#51]
Trying to get property of non-object (View: /home/user/photo/resources/views/themes/base/partials/permission_checkbox.blade.php)
in 12d68dc4b1f6d47f521ea5b4576f3520c15bfc04.php (line 2)
at CompilerEngine->handleViewException(object(ErrorException), 1)
in PhpEngine.php (line 44)

at PhpEngine->evaluatePath
in CompilerEngine.php (line 59)

at CompilerEngine->get(...show_album.blade.php)
in View.php (line 137)

This happens after creating an album. Album is created, although the error is triggered. 
Same issue when trying to Manage an album.

**Comment by pandy06269** [comment]
Does your MySQL table `permissions` have any records in it?

**Comment by cozmalaurentiu** [comment]
No, it's empty. And it seems i cannot edit it from phpMyAdmin.
The db user i created during install has all privileges. (i created it from cpanel using MySQL Databases)

**Comment by pandy06269** [comment]
Ah think I've found the problem - seems like the database isn't "seeded" on a clean install, but it is during an upgrade.

Can you change the version number in the `configuration` table to 2.1.0-beta.2, then go back into Blue Twilight. The version number should change back to 2.1.0-beta.3 automatically and you should find your `permissions` table is then populated.

![image](https://user-images.githubusercontent.com/12907944/31006825-43eb2702-a4f6-11e7-8982-e51eb3dc4062.png)

**Comment by cozmalaurentiu** [comment]
yes, it fixed the issue.

**Comment by pandy06269** [comment]
This has been fixed in the upcoming 2.1.0-beta.4.
