### ISSUE TITLE
upload photo field doesn't show selected file

### ISSUE THREAD

**Issue by cozmalaurentiu** [pandy06269/blue-twilight#52]
- Go to Manage Album - Upload tab - Upload photos individually
- Select a photo file

select field should show the selected file, it shows the same "Choose file.." placeholder.
![empty_upload_field_](https://user-images.githubusercontent.com/32333032/31007844-8b6ea05e-a50a-11e7-81a6-081bd5ef6362.jpg)

**Comment by pandy06269** [comment]
Yeah this is unfortunately a known issue with Bootstrap 4. The files are indeed selected though and will upload when you hit the button.

**Comment by pandy06269** [comment]
This has been resolved in the upcoming 2.1.0-beta.4 release by removing the Bootstrap 4 custom file pickers
