### ISSUE TITLE
Feature request: allow sub-albums to be created inside an album

### ISSUE THREAD

**Issue by cozmalaurentiu** [pandy06269/blue-twilight#53]
I didn't find a way to create an album inside another album, this would be a nice to have feature.

**Comment by cozmalaurentiu** [comment]
Ah, there already is this option, sorry.

**Comment by pandy06269** [comment]
This is indeed possible - it was introduced in version 2.0. When you create an album, you can use the "parent album" drop-down:

![image](https://user-images.githubusercontent.com/12907944/31007964-4582b89c-a4fa-11e7-9897-c1bafd1badcc.png)

You can see this on my own gallery - the Florida album is a parent album that has 4 children:

https://photos.andyheathershaw.uk/a/Florida
