### ISSUE TITLE
Album with sub-albums and no photos is shown as empty

### ISSUE THREAD

**Issue by cozmalaurentiu** [pandy06269/blue-twilight#54]
0 photos is shown in the album description, it should also show the number of sub-albums.
Also, it's treated as empty even if there are sub-albums with photos inside.

Note: sub-albums are displayed correctly, but the main album should show that it's not actually empty.

**Comment by pandy06269** [comment]
As a note whilst working on this: 1 photo is also displayed as "1 photo**s**"

**Comment by pandy06269** [comment]
Also the thumbnail for the parent album should really take into account child albums as well if the parent album has no photos.

**Comment by pandy06269** [comment]
@cozmalaurentiu please can you take a look at this link: http://blue-twilight-dev.andys.eu/

You'll see the "Test" album has no photos - however it's thumbnail has been "bought up" from one of the child albums.

It now also says "2 more albums" in the album's footer (which is only visible if there are child albums available.)

When you click onto the album, you no longer see the message that the album is empty if there are child albums available.

**Comment by cozmalaurentiu** [comment]
Yes, looks ok. What happens when first album has no photos and there is a photo in the second album?

I created an account there but i cannot create albums. :)

**Comment by pandy06269** [comment]
I've given you permission to create albums on there - that's my development system so don't be alarmed if things go missing from time-to-time ;-)

The "Test" album has no photos, but it contains a child album "Child Test" that does - which is that scenario you've described.

Thumbnails are pulled up from the child albums if the parent doesn't have any photos itself, and the parent album does not display the large "no photos" image and message, but a more subtle one with child albums more visible.

**Comment by pandy06269** [comment]
This will be in the 2.1.0-beta.4 release
