### ISSUE TITLE
Open album/manage album opens in new browser tab

### ISSUE THREAD

**Issue by cozmalaurentiu** [pandy06269/blue-twilight#56]
Two cases:
- Home - Open an album - click on "Manage album" button
- From manage album click on "Open album" button

In both cases it opens in new browser tab. I think it should open in the same window, i don't see any point in opening in separate windows.

**Comment by pandy06269** [comment]
Yeah agreed - this used to be because there was only a "open album" button in admin - so once the album was opened, you couldn't get back to the admin screen easily - hence it opening a tab.

Now we do have the link back, I agree it doesn't need to open in a new tab any longer.

**Comment by pandy06269** [comment]
Changed, will be in the 2.1.0-beta.4 release
