### ISSUE TITLE
Album breadcrumb should show full path

### ISSUE THREAD

**Issue by LNT00** [pandy06269/blue-twilight#61]
Album breadcrumb only shows 
Admin / Albums / child_album

The full path should be

Admin / Albums / parent_album / child_album

![breadcrumbs](https://user-images.githubusercontent.com/32333032/31069337-bc25b30c-a764-11e7-9bbc-62980d1576e3.jpg)

**Comment by pandy06269** [comment]
This was fixed in #30 for the gallery side - needs the same logic added to the admin side.

**Comment by pandy06269** [comment]
This has been fixed in the upcoming 2.1.1 release, and is live now on the demo site: https://demo.showmy.photos/
