### ISSUE TITLE
Album dropdown on homepage shows only the current page albums

### ISSUE THREAD

**Issue by LNT00** [pandy06269/blue-twilight#62]
Albums are displayed 12/page, so when there is pagination the Albums dropdown only shows the albums on the current page, and it should show all albums.

First page:
![albums_on_page_1](https://user-images.githubusercontent.com/32333032/31069445-2f60bb50-a765-11e7-8a29-84f9379c92fd.jpg)

Second page:
![albums_on_page_2](https://user-images.githubusercontent.com/32333032/31069452-395bda68-a765-11e7-9f07-f1a45a760dfc.jpg)

**Comment by pandy06269** [comment]
Ooh good spot, I haven't noticed this before.

**Comment by pandy06269** [comment]
This has been fixed in 2.1.1, live now on the demo site at https://demo.showmy.photos
