### ISSUE TITLE
/admin returns 500 Internal Server Error

### ISSUE THREAD

**Issue by LNT00** [pandy06269/blue-twilight#63]
At some point /admin stopped working and returns 500 Internal Server Error.
/admin/albums is working correctly.

I see the same issue on the dev site, /admin is working, but /admin/albums is not working.

**Comment by pandy06269** [comment]
Both /admin and /admin/albums are working fine for me on the dev site.

Is there anything helpful logged in your log file - in `blue-twilight/storage/logs` (date stamped)?

Also do you see a screen that says "500 Internal Server Error" or do you see a white screen with a red bar that says "an error occurred"?

**Comment by LNT00** [comment]
I only see  500 Internal Server Error, and the same on dev.

I have a lot of issue in logs.
[erros.txt](https://github.com/pandy06269/blue-twilight/files/1349179/erros.txt)

**Comment by LNT00** [comment]
I found this in root/error_log:
[02-Oct-2017 15:35:02 America/New_York] PHP Warning:  system() has been disabled for security reasons in /public/update.php on line 98

and from public/error_log:
[02-Oct-2017 20:35:03 Europe/London] PHP Fatal error:  Allowed memory size of 67108864 bytes exhausted (tried to allocate 32 bytes) in /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 142

**Comment by pandy06269** [comment]
I'm really struggling to see what's wrong here. I can access /admin/albums just fine on the dev site - and there are no errors logged for today at all. The last message was logged around 30 hours ago.

<img width="1318" alt="screen shot 2017-10-02 at 21 32 19" src="https://user-images.githubusercontent.com/12907944/31098099-6e7b3640-a7b9-11e7-94f9-568d837c4649.png">

Is there something in particular you're doing that's triggering the error?

Also it would be helpful to [turn off Internet Explorer's "friendly errors"](https://blogs.msdn.microsoft.com/ieinternals/2010/08/18/friendly-http-error-pages/) as this may be hiding the actual error.

**Comment by LNT00** [comment]
No idea really why that is happening. And what is strange is that it also happening on your dev, where i didn't make any changes.

I tried /admin/users (direct link) and this also works, so it's strange why /admin is not working

**Comment by LNT00** [comment]
I opened a ticket at my hosting company and they seem to have fixed the problem, /admin is now working. So it's not an app issue, rather a hosting issue. It was clear since /admin/albums was working.

I think this can be closed.

**Comment by pandy06269** [comment]
Ok great. 500 is definitely a server side issue but I would have been really interested to see the actual error page as it was returned from the server.

Unfortunately Internet Explorer display its own “friendly” error page which isn’t much help, that’s why I’d asked you to turn off friendly error messages so I could try and work out what it was.

I couldn’t see any 500 errors in my dev logs so have no idea what was happening!

**Comment by andysh-uk** [comment]
FYI, I believe #84 resolves this - I came across a similar issue when logged in as a non-admin user account. It has been resolved in v2.1.2.
