### ISSUE TITLE
Both uploading buttons are displayed as uploading

### ISSUE THREAD

**Issue by LNT00** [pandy06269/blue-twilight#67]
Steps:
1. Go to Manage - Albums - click on an album - upload tab
2. Select a photo file and upload it.

Both "Upload" buttons are now displayed as "Uploading in progress...". Only the first button should show this message.

![active_button](https://user-images.githubusercontent.com/32333032/31124880-f6da0792-a84e-11e7-9961-5e6961596f5e.jpg)

**Comment by pandy06269** [comment]
This is by design because an upload is in progress, so you can’t start another one, irrespective of which method you used.

**Comment by LNT00** [comment]
From the usability point of view it's confusing. Ideally only the active button should show the state of the action. Because of the overlay, user can't use either buttons, so that would be a problem.
