### ISSUE TITLE
Statistics on /admin is incorrect, it only counts the root albums, it should count all the albums

### ISSUE THREAD

**Issue by LNT00** [pandy06269/blue-twilight#72]
Not sure if this is intended, but it seems incorrect to me:

/admin statistics:
![admin_stats](https://user-images.githubusercontent.com/32333032/31178080-a094c980-a920-11e7-88e2-5acdb7e4b626.jpg)

/statistics:
![statistics_stats](https://user-images.githubusercontent.com/32333032/31178090-b1dcb0fe-a920-11e7-9bf8-0ace817c72ed.jpg)

The one from statistics page is correct, and i think it should also show the correct value on /admin page.

**Comment by pandy06269** [comment]
Completely agree, the admin stats should reflect total albums the same as the stats screen.

**Comment by pandy06269** [comment]
This has been fixed in 2.1.1 and is on the demo system (https://demo.showmy.photos.)  This was due to the stats widget in the admin screen using paging, so it was only showing 12 albums when you had >12.  The stats page was correct.
