### ISSUE TITLE
Update metadata should not apply to empty albums

### ISSUE THREAD

**Issue by LNT00** [pandy06269/blue-twilight#75]
Empty albums (0 photos) should be excluded from update:

![meta_empty_1](https://user-images.githubusercontent.com/32333032/31223823-3916b3b8-a9d4-11e7-80da-6e1d081b3e0d.jpg)

and trying to update leads nowhere, since there is nothing to update:

![meta_empty_2](https://user-images.githubusercontent.com/32333032/31223852-4abcf154-a9d4-11e7-96c4-e15d83bd5a5f.jpg)

**Comment by pandy06269** [comment]
This has been resolved in 2.1.1
